name: Python CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lock_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Sync dependencies
        run: uv sync --locked --all-extras --dev

  linting:
    runs-on: ubuntu-latest
    needs: lock_file
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Lint with Ruff
        run: uvx ruff check .

  formatting:
    runs-on: ubuntu-latest
    needs: lock_file
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Check code formatting
        run: uvx ruff format --check .

  type_consistency:
    runs-on: ubuntu-latest
    needs: lock_file
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Check types with Pyright
        run: uv run pyright .

  static_analysis:
    runs-on: ubuntu-latest
    needs: lock_file
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Run Bandit
        run: uv run bandit -r app

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1

  tests:
    runs-on: ubuntu-latest
    needs: lock_file
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Run tests with coverage
        run: |
          uv run coverage run -m pytest -v --durations=0
          uv run coverage report
          uv run coverage xml

  build:
    runs-on: ubuntu-latest
    needs: [linting, formatting, type_consistency, static_analysis, tests]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Build project
        run: uv build

  dast:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start services
        run: docker-compose up -d

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: "http://localhost:8000"
