name: Python CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
  install_uv:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@v5
  install_dependencies:
    runs-on: ubuntu-latest
    needs: [install_uv]
    steps:
      - name: Install dependencies
        run: uv sync --locked --all-extras --dev

  ruff_linting:
    runs-on: ubuntu-latest
    needs: [install_dependencies]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: uvx ruff check .
