name: Python CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync --locked --all-extras --dev

      - name: Lint with ruff
        uses: astral-sh/ruff-action@v3
        run: ruff check --fix
        run: ruff format

      - name: Format with black
        run: black --check app tests

      - name: Static Analysis with Bandit
        run: bandit -r app

      - name: Static Analysis with Semgrep
        uses: returntocorp/semgrep-action@v1

      - name: Run tests with coverage
        run: |
          coverage run -m pytest
          coverage report
          coverage xml

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v4
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     files: ./coverage.xml

  dast:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start services
        run: docker-compose up -d

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: "http://localhost:8000"
