name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # Adjust to your project's Python version

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Create virtual environment and install dependencies
        uses: .github/actions/setup

      - name: Lint and check formatting with Ruff
        run: |
          source .venv/bin/activate
          ruff check .
          ruff format --check .

      - name: Run tests with Pytest
        run: |
          source .venv/bin/activate
          pytest

  zap_scan:
    runs-on: ubuntu-latest
    needs: build  # Run DAST only after build/tests

    steps:
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://localhost:8000'  # Update with the URL of your deployed/staging app